### PR TITLE
CA-771 - added a thank you page for project creation.

### PR DESCRIPTION
**Pull request by phistuck**

### CODE REVIEW

**Comment by phistuck** [comment]
Let me know whether this is the right direction...

**Comment by ljwboschker** [comment]
Looks good to me. @arnoutj any comments from you?

**Comment by phistuck** [comment]
@ronvdakker, for your information, this how it looks on desktop -
image
Mobile -
image

@arnoutj - I think I fixed all of the comments.

@timstokman - are the TravisCI failures expected at this point?

**Comment by timstokman** [comment]
@phistuck One of the integration tests is failing. You can ignore it for now.

**Comment by ronvdakker** [comment]
Thanks! Huge improvement to current page. Not entirely sure about the image
yet, but for now it's fine and I'll give it some thought and maybe ask the
designers for ideas once they're done w the other designs.
Thanks!

**Pull request merged**
